"""ad

Revision ID: 0d4d6b61362a
Revises: c9de51371b65
Create Date: 2023-09-17 17:20:04.671265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d4d6b61362a'
down_revision: Union[str, None] = 'c9de51371b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notes_board_id_fkey', 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key('notes_board_id_fkey', 'notes', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###
